providers = ["node"]

[phases.setup]
nixPkgs = ["...","yarn"]

[phases.install]
cmds = ["yarn install --frozen-lockfile"]

[phases.build]
cmds = ["yarn build"]

[start]
cmd = "sleep 5s && yarn start"
